version: '3'

services:
  shirim:
    image: theteamaker/shirim
    environment:
      - TOKEN=<secret>
      - LASTFM_API_KEY=<secret>
      - YOUTUBE_API_KEY=<secret>
      - USERS_DB=sqlite:///data/users.db
      - SERVERS_DB=sqlite:///data/servers.db
      - YOUTUBE_API_KEY=<secret>
    
    volumes:
      - shirim_data:/app/data
    
volumes:
  shirim_data:
    external: true