version: '3'

services:
  shirim:
    image: theteamaker/shirim
    environment:
      - TOKEN=<secret>
      - LASTFM_API_KEY=<secret>
      - SQL_DATABASE=sqlite:///users.db
    volumes:
      - shirim_data:/app/data
    
volumes:
  shirim_data:
    external: true
